### ISSUE TITLE
Beta 1 Staging Checklist

### ISSUE THREAD

**Issue by EricRabil** [CastProject/Cask#9]
- [x] Verify that permissions work for users, roles and guild members

- [x] Verify that plugins are properly enabled/disabled in guilds, and have a command to do so

- [x] Verify that commands that specify `globalAdminOnly` are only accessible to Global Admins

- [x] Verify that `reloadAll` on containers will truly reload from the file itself, allowing for code changes

- [x] Verify that `setEnabled` on `CaskGuildManager` works as expected

- [x] Implement `allRemaining` for command type-definitions

Let the games begin 🔥 ✨
